### ISSUE TITLE
PySSA: Strange memory leak

### ISSUE THREAD

**Issue by sppmacd** [Adam-Ratajczak/2d-solar-system-simulator#3]
reproduce:
```py
import pyssa
o = pyssa.Object(pyssa.world) # This must be assigned
pyssa.Object(1) # Run invalid constructor, doesn't need to be assigned.
```

The order of two last lines is not significant.
Checkout the `pyssa-leak` branch for debug messages.

```
EVAL >>> import pyssa
setup_python_bindings!!
Decreffing 0x55d5e17fdf20, refcount=3750
EVAL >>> o = pyssa.Object(pyssa.world)
Decreffing 0x7fbf37e61d00, refcount=5
Decreffing 0x7fbf37e4e080, refcount=2
### 0x6160002ba180 created for 0x6160002b9ba0
Decreffing 0x55d5e17fdf20, refcount=3749
EVAL >>> p = pyssa.Object(1)
Decreffing 0x7fbf37e4e080, refcount=2
ERROR!!
Decreffing 0x7fbf37e78640, refcount=2
Decreffing 0x7fbf37e79070, refcount=2
Decreffing 0x7fbf52b58d40, refcount=9
Decreffing 0x7fbf37e7c3d0, refcount=3
Decreffing 0x7fbf37e613b0, refcount=3
Decreffing 0x7fbf37813ac0, refcount=2
Decreffing 0x7fbf37e7daf0, refcount=4
Decreffing 0x7fbf37e7cd60, refcount=3
Decreffing 0x7fbf377de740, refcount=3
Decreffing 0x7fbf37e61fe0, refcount=1
Decreffing 0x7fbf37e78710, refcount=2
Before Py_FinalizeEx
Before Py_FinalizeEx but after decreffing
After Py_FinalizeEx


=================================================================
==2230==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 15098 byte(s) in 8 object(s) allocated from:
    #0 0x7fbf52fb3dd9 in __interceptor_malloc /usr/src/debug/gcc/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7fbf5280ecbd in _PyMem_RawMalloc Objects/obmalloc.c:101

Direct leak of 6240 byte(s) in 3 object(s) allocated from:
    #0 0x7fbf52fb3fb9 in __interceptor_calloc /usr/src/debug/gcc/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x7fbf4c717b7f in amdgpu_winsys_create (/usr/lib/dri/radeonsi_dri.so+0x9e7b7f)

Indirect leak of 40960 byte(s) in 1 object(s) allocated from:
    #0 0x7fbf52fb5811 in operator new(unsigned long) /usr/src/debug/gcc/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x55d5e106a252 in __gnu_cxx::new_allocator<Vertex>::allocate(unsigned long, void const*) /usr/include/c++/11.2.0/ext/new_allocator.h:127
    #2 0x55d5e10655ca in std::allocator<Vertex>::allocate(unsigned long) /usr/include/c++/11.2.0/bits/allocator.h:197
    #3 0x55d5e10655ca in std::allocator_traits<std::allocator<Vertex> >::allocate(std::allocator<Vertex>&, unsigned long) /usr/include/c++/11.2.0/bits/alloc_traits.h:460
    #4 0x55d5e1060c11 in std::_Vector_base<Vertex, std::allocator<Vertex> >::_M_allocate(unsigned long) /usr/include/c++/11.2.0/bits/stl_vector.h:346
    #5 0x55d5e108d2e8 in void std::vector<Vertex, std::allocator<Vertex> >::_M_realloc_insert<Vertex>(__gnu_cxx::__normal_iterator<Vertex*, std::vector<Vertex, std::allocator<Vertex> > >, Vertex&&) /usr/include/c++/11.2.0/bits/vector.tcc:440
    #6 0x55d5e108c99a in Vertex& std::vector<Vertex, std::allocator<Vertex> >::emplace_back<Vertex>(Vertex&&) /usr/include/c++/11.2.0/bits/vector.tcc:121
    #7 0x55d5e108b7d9 in std::vector<Vertex, std::allocator<Vertex> >::push_back(Vertex&&) /usr/include/c++/11.2.0/bits/stl_vector.h:1204
    #8 0x55d5e1088d14 in Sphere::gen_sphere() /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/glwrapper/Sphere.cpp:33
    #9 0x55d5e10884ac in Sphere::Sphere(double, int, int) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/glwrapper/Sphere.cpp:20
    #10 0x55d5e103ac3c in Object::Object(World&, double, double, Vector3, Vector3, sf::Color, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/Object.cpp:30
    #11 0x55d5e104eca1 in Object::create_for_python(PySSA::Object const&, PySSA::Object const&) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/Object.cpp:312
    #12 0x55d5e1062e4d in PySSA::WrappedObject<Object>::setup_python_bindings_internal(_typeobject&)::{lambda(_typeobject*, _object*, _object*)#2}::operator()(_typeobject*, _object*, _object*) const /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/pyssa/../pyssa/WrappedObject.hpp:143
    #13 0x55d5e106355d in PySSA::WrappedObject<Object>::setup_python_bindings_internal(_typeobject&)::{lambda(_typeobject*, _object*, _object*)#2}::_FUN(_typeobject*, _object*, _object*) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/pyssa/../pyssa/WrappedObject.hpp:142
    #14 0x7fbf5282e3b8 in type_call Objects/typeobject.c:1104

Indirect leak of 32768 byte(s) in 1 object(s) allocated from:
    #0 0x7fbf52fb5811 in operator new(unsigned long) /usr/src/debug/gcc/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x55d5e108fa20 in __gnu_cxx::new_allocator<unsigned int>::allocate(unsigned long, void const*) /usr/include/c++/11.2.0/ext/new_allocator.h:127
    #2 0x55d5e108f64e in std::allocator<unsigned int>::allocate(unsigned long) /usr/include/c++/11.2.0/bits/allocator.h:197
    #3 0x55d5e108f64e in std::allocator_traits<std::allocator<unsigned int> >::allocate(std::allocator<unsigned int>&, unsigned long) /usr/include/c++/11.2.0/bits/alloc_traits.h:460
    #4 0x55d5e108f279 in std::_Vector_base<unsigned int, std::allocator<unsigned int> >::_M_allocate(unsigned long) /usr/include/c++/11.2.0/bits/stl_vector.h:346
    #5 0x55d5e108e0aa in void std::vector<unsigned int, std::allocator<unsigned int> >::_M_realloc_insert<unsigned int>(__gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int, std::allocator<unsigned int> > >, unsigned int&&) /usr/include/c++/11.2.0/bits/vector.tcc:440
    #6 0x55d5e108cdc6 in unsigned int& std::vector<unsigned int, std::allocator<unsigned int> >::emplace_back<unsigned int>(unsigned int&&) /usr/include/c++/11.2.0/bits/vector.tcc:121
    #7 0x55d5e108b885 in std::vector<unsigned int, std::allocator<unsigned int> >::push_back(unsigned int&&) /usr/include/c++/11.2.0/bits/stl_vector.h:1204
    #8 0x55d5e108944b in Sphere::gen_sphere() /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/glwrapper/Sphere.cpp:42
    #9 0x55d5e10884ac in Sphere::Sphere(double, int, int) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/glwrapper/Sphere.cpp:20
    #10 0x55d5e103ac3c in Object::Object(World&, double, double, Vector3, Vector3, sf::Color, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/Object.cpp:30
    #11 0x55d5e104eca1 in Object::create_for_python(PySSA::Object const&, PySSA::Object const&) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/Object.cpp:312
    #12 0x55d5e1062e4d in PySSA::WrappedObject<Object>::setup_python_bindings_internal(_typeobject&)::{lambda(_typeobject*, _object*, _object*)#2}::operator()(_typeobject*, _object*, _object*) const /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/pyssa/../pyssa/WrappedObject.hpp:143
    #13 0x55d5e106355d in PySSA::WrappedObject<Object>::setup_python_bindings_internal(_typeobject&)::{lambda(_typeobject*, _object*, _object*)#2}::_FUN(_typeobject*, _object*, _object*) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/pyssa/../pyssa/WrappedObject.hpp:142
    #14 0x7fbf5282e3b8 in type_call Objects/typeobject.c:1104

Indirect leak of 584 byte(s) in 1 object(s) allocated from:
    #0 0x7fbf52fb5811 in operator new(unsigned long) /usr/src/debug/gcc/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x55d5e104ea8e in Object::create_for_python(PySSA::Object const&, PySSA::Object const&) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/Object.cpp:312
    #2 0x55d5e1062e4d in PySSA::WrappedObject<Object>::setup_python_bindings_internal(_typeobject&)::{lambda(_typeobject*, _object*, _object*)#2}::operator()(_typeobject*, _object*, _object*) const /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/pyssa/../pyssa/WrappedObject.hpp:143
    #3 0x55d5e106355d in PySSA::WrappedObject<Object>::setup_python_bindings_internal(_typeobject&)::{lambda(_typeobject*, _object*, _object*)#2}::_FUN(_typeobject*, _object*, _object*) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/pyssa/../pyssa/WrappedObject.hpp:142
    #4 0x7fbf5282e3b8 in type_call Objects/typeobject.c:1104

Indirect leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x7fbf52fb5811 in operator new(unsigned long) /usr/src/debug/gcc/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x55d5e106a252 in __gnu_cxx::new_allocator<Vertex>::allocate(unsigned long, void const*) /usr/include/c++/11.2.0/ext/new_allocator.h:127
    #2 0x55d5e10655ca in std::allocator<Vertex>::allocate(unsigned long) /usr/include/c++/11.2.0/bits/allocator.h:197
    #3 0x55d5e10655ca in std::allocator_traits<std::allocator<Vertex> >::allocate(std::allocator<Vertex>&, unsigned long) /usr/include/c++/11.2.0/bits/alloc_traits.h:460
    #4 0x55d5e1060c11 in std::_Vector_base<Vertex, std::allocator<Vertex> >::_M_allocate(unsigned long) /usr/include/c++/11.2.0/bits/stl_vector.h:346
    #5 0x55d5e105beec in std::vector<Vertex, std::allocator<Vertex> >::_M_default_append(unsigned long) /usr/include/c++/11.2.0/bits/vector.tcc:635
    #6 0x55d5e1056e67 in std::vector<Vertex, std::allocator<Vertex> >::resize(unsigned long) /usr/include/c++/11.2.0/bits/stl_vector.h:940
    #7 0x55d5e103b763 in Object::Object(World&, double, double, Vector3, Vector3, sf::Color, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/Object.cpp:40
    #8 0x55d5e104eca1 in Object::create_for_python(PySSA::Object const&, PySSA::Object const&) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/Object.cpp:312
    #9 0x55d5e1062e4d in PySSA::WrappedObject<Object>::setup_python_bindings_internal(_typeobject&)::{lambda(_typeobject*, _object*, _object*)#2}::operator()(_typeobject*, _object*, _object*) const /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/pyssa/../pyssa/WrappedObject.hpp:143
    #10 0x55d5e106355d in PySSA::WrappedObject<Object>::setup_python_bindings_internal(_typeobject&)::{lambda(_typeobject*, _object*, _object*)#2}::_FUN(_typeobject*, _object*, _object*) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/pyssa/../pyssa/WrappedObject.hpp:142
    #11 0x7fbf5282e3b8 in type_call Objects/typeobject.c:1104

Indirect leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x7fbf52fb5811 in operator new(unsigned long) /usr/src/debug/gcc/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7fbf52d5b743 in sf::VertexArray::VertexArray(sf::PrimitiveType, unsigned long) (/usr/lib/libsfml-graphics.so.2.5+0x4f743)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7fbf52fb5811 in operator new(unsigned long) /usr/src/debug/gcc/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x55d5e1039e08 in __gnu_cxx::new_allocator<Entry>::allocate(unsigned long, void const*) (/home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/build/out+0x491e08)
    #2 0x55d5e10399e0 in std::allocator_traits<std::allocator<Entry> >::allocate(std::allocator<Entry>&, unsigned long) (/home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/build/out+0x4919e0)
    #3 0x55d5e10395d1 in std::_Vector_base<Entry, std::allocator<Entry> >::_M_allocate(unsigned long) (/home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/build/out+0x4915d1)
    #4 0x55d5e1038779 in std::vector<Entry, std::allocator<Entry> >::_M_default_append(unsigned long) (/home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/build/out+0x490779)
    #5 0x55d5e1037de5 in std::vector<Entry, std::allocator<Entry> >::resize(unsigned long) (/home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/build/out+0x48fde5)
    #6 0x55d5e10375f6 in History::Node::Node(History::Node*, History::Node*, unsigned int) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/History.hpp:22
    #7 0x55d5e10332f2 in History::History(unsigned int, Entry) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/History.cpp:4
    #8 0x55d5e103a602 in Object::Object(World&, double, double, Vector3, Vector3, sf::Color, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/Object.cpp:31
    #9 0x55d5e104eca1 in Object::create_for_python(PySSA::Object const&, PySSA::Object const&) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/Object.cpp:312
    #10 0x55d5e1062e4d in PySSA::WrappedObject<Object>::setup_python_bindings_internal(_typeobject&)::{lambda(_typeobject*, _object*, _object*)#2}::operator()(_typeobject*, _object*, _object*) const /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/pyssa/../pyssa/WrappedObject.hpp:143
    #11 0x55d5e106355d in PySSA::WrappedObject<Object>::setup_python_bindings_internal(_typeobject&)::{lambda(_typeobject*, _object*, _object*)#2}::_FUN(_typeobject*, _object*, _object*) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/pyssa/../pyssa/WrappedObject.hpp:142
    #12 0x7fbf5282e3b8 in type_call Objects/typeobject.c:1104

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7fbf52fb5811 in operator new(unsigned long) /usr/src/debug/gcc/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x55d5e1071d47 in __gnu_cxx::new_allocator<std::_List_node<Vector3> >::allocate(unsigned long, void const*) /usr/include/c++/11.2.0/ext/new_allocator.h:127
    #2 0x55d5e1071c96 in std::allocator<std::_List_node<Vector3> >::allocate(unsigned long) /usr/include/c++/11.2.0/bits/allocator.h:197
    #3 0x55d5e1071c96 in std::allocator_traits<std::allocator<std::_List_node<Vector3> > >::allocate(std::allocator<std::_List_node<Vector3> >&, unsigned long) /usr/include/c++/11.2.0/bits/alloc_traits.h:460
    #4 0x55d5e10716e8 in std::__cxx11::_List_base<Vector3, std::allocator<Vector3> >::_M_get_node() /usr/include/c++/11.2.0/bits/stl_list.h:442
    #5 0x55d5e10712d4 in std::_List_node<Vector3>* std::__cxx11::list<Vector3, std::allocator<Vector3> >::_M_create_node<Vector3 const&>(Vector3 const&) /usr/include/c++/11.2.0/bits/stl_list.h:634
    #6 0x55d5e1070b8a in void std::__cxx11::list<Vector3, std::allocator<Vector3> >::_M_insert<Vector3 const&>(std::_List_iterator<Vector3>, Vector3 const&) /usr/include/c++/11.2.0/bits/stl_list.h:1911
    #7 0x55d5e10707ab in std::__cxx11::list<Vector3, std::allocator<Vector3> >::push_back(Vector3 const&) /usr/include/c++/11.2.0/bits/stl_list.h:1212
    #8 0x55d5e106fb46 in Trail::push_back(Vector3 const&) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/Trail.cpp:15
    #9 0x55d5e103ba5b in Object::Object(World&, double, double, Vector3, Vector3, sf::Color, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/Object.cpp:43
    #10 0x55d5e104eca1 in Object::create_for_python(PySSA::Object const&, PySSA::Object const&) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/Object.cpp:312
    #11 0x55d5e1062e4d in PySSA::WrappedObject<Object>::setup_python_bindings_internal(_typeobject&)::{lambda(_typeobject*, _object*, _object*)#2}::operator()(_typeobject*, _object*, _object*) const /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/pyssa/../pyssa/WrappedObject.hpp:143
    #12 0x55d5e106355d in PySSA::WrappedObject<Object>::setup_python_bindings_internal(_typeobject&)::{lambda(_typeobject*, _object*, _object*)#2}::_FUN(_typeobject*, _object*, _object*) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/pyssa/../pyssa/WrappedObject.hpp:142
    #13 0x7fbf5282e3b8 in type_call Objects/typeobject.c:1104

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7fbf52fb5811 in operator new(unsigned long) /usr/src/debug/gcc/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x55d5e103321e in History::History(unsigned int, Entry) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/History.cpp:4
    #2 0x55d5e103a602 in Object::Object(World&, double, double, Vector3, Vector3, sf::Color, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/Object.cpp:31
    #3 0x55d5e104eca1 in Object::create_for_python(PySSA::Object const&, PySSA::Object const&) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/Object.cpp:312
    #4 0x55d5e1062e4d in PySSA::WrappedObject<Object>::setup_python_bindings_internal(_typeobject&)::{lambda(_typeobject*, _object*, _object*)#2}::operator()(_typeobject*, _object*, _object*) const /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/pyssa/../pyssa/WrappedObject.hpp:143
    #5 0x55d5e106355d in PySSA::WrappedObject<Object>::setup_python_bindings_internal(_typeobject&)::{lambda(_typeobject*, _object*, _object*)#2}::_FUN(_typeobject*, _object*, _object*) /home/sppmacd/Prog/Herbatka/2d-solar-system-simulator/src/pyssa/../pyssa/WrappedObject.hpp:142
    #6 0x7fbf5282e3b8 in type_call Objects/typeobject.c:1104

SUMMARY: AddressSanitizer: 95970 byte(s) leaked in 19 allocation(s).
```

**Comment by sppmacd** [comment]
Every kind of exception causes this leak:
```python
o = pyssa.Object()  #properly create object
w #refer to undefined variable
```
